services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Makoso\DatagridBundle\:
        resource: './../../*'
        exclude: './../../Grid/Column'
    Makoso\DatagridBundle\Grid\Grid:
        public: true